// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicListGridSwitch,
  DefaultListGridSwitchProps
} from "./plasmic/hub_hub/PlasmicListGridSwitch";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ListGridSwitchProps extends Omit<DefaultListGridSwitchProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultListGridSwitchProps altogether and have
// total control over the props for your component.
interface ListGridSwitchProps extends DefaultListGridSwitchProps {}

function ListGridSwitch_(
  props: ListGridSwitchProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicListGridSwitch to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicListGridSwitch are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all ListGridSwitchProps here, but feel free
  // to do whatever works for you.

  return <PlasmicListGridSwitch root={{ ref }} {...props} />;
}

const ListGridSwitch = React.forwardRef(ListGridSwitch_);
export default ListGridSwitch;
