// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicOptionsIcon,
  DefaultOptionsIconProps
} from "./plasmic/hub_hub/PlasmicOptionsIcon";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface OptionsIconProps extends Omit<DefaultOptionsIconProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultOptionsIconProps altogether and have
// total control over the props for your component.
interface OptionsIconProps extends DefaultOptionsIconProps {}

function OptionsIcon_(props: OptionsIconProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicOptionsIcon to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicOptionsIcon are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all OptionsIconProps here, but feel free
  // to do whatever works for you.

  return <PlasmicOptionsIcon root={{ ref }} {...props} />;
}

const OptionsIcon = React.forwardRef(OptionsIcon_);
export default OptionsIcon;
