// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 24qDGfvb2rMn6oy8PVF95d
// Component: wWoXZuP3yV
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_hub_hub.module.css"; // plasmic-import: 24qDGfvb2rMn6oy8PVF95d/projectcss
import * as sty from "./PlasmicHubItem.module.css"; // plasmic-import: wWoXZuP3yV/css

export type PlasmicHubItem__VariantMembers = {};

export type PlasmicHubItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicHubItem__VariantsArgs;
export const PlasmicHubItem__VariantProps = new Array<VariantPropType>();

export type PlasmicHubItem__ArgsType = {
  hubTitle?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHubItem__ArgsType;
export const PlasmicHubItem__ArgProps = new Array<ArgPropType>("hubTitle");

export type PlasmicHubItem__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHubItemProps {
  hubTitle?: React.ReactNode;
  className?: string;
}

function PlasmicHubItem__RenderFunc(props: {
  variants: PlasmicHubItem__VariantsArgs;
  args: PlasmicHubItem__ArgsType;
  overrides: PlasmicHubItem__OverridesType;
  dataFetches?: PlasmicHubItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Science News",
        value: args.hubTitle,
        className: classNames(sty.slotHubTitle)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHubItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHubItem__VariantsArgs;
    args?: PlasmicHubItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHubItem__Fetches;
  } & Omit<PlasmicHubItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHubItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHubItem__ArgProps,
      internalVariantPropNames: PlasmicHubItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHubItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHubItem";
  } else {
    func.displayName = `PlasmicHubItem.${nodeName}`;
  }
  return func;
}

export const PlasmicHubItem = Object.assign(
  // Top-level PlasmicHubItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHubItem
    internalVariantProps: PlasmicHubItem__VariantProps,
    internalArgProps: PlasmicHubItem__ArgProps
  }
);

export default PlasmicHubItem;
/* prettier-ignore-end */
