// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 24qDGfvb2rMn6oy8PVF95d
// Component: 5JnDz-tqZ8
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_hub_hub.module.css"; // plasmic-import: 24qDGfvb2rMn6oy8PVF95d/projectcss
import * as sty from "./PlasmicGridModeIcon.module.css"; // plasmic-import: 5JnDz-tqZ8/css

export type PlasmicGridModeIcon__VariantMembers = {
  selected: "selected";
  color: "blue" | "red";
};

export type PlasmicGridModeIcon__VariantsArgs = {
  selected?: SingleBooleanChoiceArg<"selected">;
  color?: SingleChoiceArg<"blue" | "red">;
};

type VariantPropType = keyof PlasmicGridModeIcon__VariantsArgs;
export const PlasmicGridModeIcon__VariantProps = new Array<VariantPropType>(
  "selected",
  "color"
);

export type PlasmicGridModeIcon__ArgsType = {};
type ArgPropType = keyof PlasmicGridModeIcon__ArgsType;
export const PlasmicGridModeIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicGridModeIcon__OverridesType = {
  root?: p.Flex<"div">;
  iconGridView?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
  rectangle27?: p.Flex<"div">;
  rectangle28?: p.Flex<"div">;
  rectangle30?: p.Flex<"div">;
};

export interface DefaultGridModeIconProps {
  selected?: SingleBooleanChoiceArg<"selected">;
  color?: SingleChoiceArg<"blue" | "red">;
  className?: string;
}

function PlasmicGridModeIcon__RenderFunc(props: {
  variants: PlasmicGridModeIcon__VariantsArgs;
  args: PlasmicGridModeIcon__ArgsType;
  overrides: PlasmicGridModeIcon__OverridesType;
  dataFetches?: PlasmicGridModeIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__selected]: hasVariant(variants, "selected", "selected")
      })}
    >
      <div
        data-plasmic-name={"iconGridView"}
        data-plasmic-override={overrides.iconGridView}
        className={classNames(defaultcss.all, sty.iconGridView)}
      >
        <div
          data-plasmic-name={"rectangle25"}
          data-plasmic-override={overrides.rectangle25}
          className={classNames(defaultcss.all, sty.rectangle25, {
            [sty.rectangle25__color_red]: hasVariant(variants, "color", "red"),
            [sty.rectangle25__selected]: hasVariant(
              variants,
              "selected",
              "selected"
            )
          })}
        />

        <div
          data-plasmic-name={"rectangle26"}
          data-plasmic-override={overrides.rectangle26}
          className={classNames(defaultcss.all, sty.rectangle26, {
            [sty.rectangle26__color_red]: hasVariant(variants, "color", "red")
          })}
        />

        <div
          data-plasmic-name={"rectangle27"}
          data-plasmic-override={overrides.rectangle27}
          className={classNames(defaultcss.all, sty.rectangle27, {
            [sty.rectangle27__color_red]: hasVariant(variants, "color", "red")
          })}
        />

        <div
          data-plasmic-name={"rectangle28"}
          data-plasmic-override={overrides.rectangle28}
          className={classNames(defaultcss.all, sty.rectangle28)}
        />
      </div>

      {(hasVariant(variants, "selected", "selected") ? true : false) ? (
        <div
          data-plasmic-name={"rectangle30"}
          data-plasmic-override={overrides.rectangle30}
          className={classNames(defaultcss.all, sty.rectangle30, {
            [sty.rectangle30__selected]: hasVariant(
              variants,
              "selected",
              "selected"
            )
          })}
        />
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "iconGridView",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "rectangle30"
  ],
  iconGridView: [
    "iconGridView",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle28"
  ],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  rectangle30: ["rectangle30"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  iconGridView: "div";
  rectangle25: "div";
  rectangle26: "div";
  rectangle27: "div";
  rectangle28: "div";
  rectangle30: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGridModeIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGridModeIcon__VariantsArgs;
    args?: PlasmicGridModeIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicGridModeIcon__Fetches;
  } & Omit<PlasmicGridModeIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicGridModeIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicGridModeIcon__ArgProps,
      internalVariantPropNames: PlasmicGridModeIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicGridModeIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGridModeIcon";
  } else {
    func.displayName = `PlasmicGridModeIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicGridModeIcon = Object.assign(
  // Top-level PlasmicGridModeIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iconGridView: makeNodeComponent("iconGridView"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle30: makeNodeComponent("rectangle30"),

    // Metadata about props expected for PlasmicGridModeIcon
    internalVariantProps: PlasmicGridModeIcon__VariantProps,
    internalArgProps: PlasmicGridModeIcon__ArgProps
  }
);

export default PlasmicGridModeIcon;
/* prettier-ignore-end */
