// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 24qDGfvb2rMn6oy8PVF95d
// Component: NsqqImYviY
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { ThemeValue, useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: 40N_XXvhaC/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_hub_hub.module.css"; // plasmic-import: 24qDGfvb2rMn6oy8PVF95d/projectcss
import * as sty from "./PlasmicTwitterItem2.module.css"; // plasmic-import: NsqqImYviY/css

import IconarrowIosLeft2Icon from "./icons/PlasmicIcon__IconarrowIosLeft2"; // plasmic-import: Snqml0Rz7e/icon
import _27IconheartFillIcon from "./icons/PlasmicIcon___27IconheartFill"; // plasmic-import: kGUtMm7VKf/icon
import _27IconrepeatIcon from "./icons/PlasmicIcon___27Iconrepeat"; // plasmic-import: DXysMN739Bs/icon
import ellipse23PmI6Z3B0Xj from "./images/ellipse23.svg"; // plasmic-import: PmI6Z3B0XJ/picture

export type PlasmicTwitterItem2__VariantMembers = {
  composition: "collapseImage" | "noImage";
};

export type PlasmicTwitterItem2__VariantsArgs = {
  composition?: SingleChoiceArg<"collapseImage" | "noImage">;
};

type VariantPropType = keyof PlasmicTwitterItem2__VariantsArgs;
export const PlasmicTwitterItem2__VariantProps = new Array<VariantPropType>(
  "composition"
);

export type PlasmicTwitterItem2__ArgsType = {
  userName?: React.ReactNode;
  twitterHandle?: React.ReactNode;
  body?: React.ReactNode;
  image?: React.ReactNode;
  likes?: React.ReactNode;
  retweets?: React.ReactNode;
  date?: React.ReactNode;
  time?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTwitterItem2__ArgsType;
export const PlasmicTwitterItem2__ArgProps = new Array<ArgPropType>(
  "userName",
  "twitterHandle",
  "body",
  "image",
  "likes",
  "retweets",
  "date",
  "time"
);

export type PlasmicTwitterItem2__OverridesType = {
  root?: p.Flex<"div">;
  contentTwitterPost3Image?: p.Flex<"div">;
  twitterPostUser?: p.Flex<"div">;
  twitterUserContainer?: p.Flex<"div">;
  twitterUserImage?: p.Flex<"img">;
  twitterUserData?: p.Flex<"div">;
  body?: p.Flex<"div">;
  showImage?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  imageContainer?: p.Flex<"div">;
  image?: p.Flex<"div">;
  twitterPostMetaData?: p.Flex<"div">;
  frame216?: p.Flex<"div">;
  group299?: p.Flex<"div">;
  likesContainer?: p.Flex<"div">;
  heartIcon?: p.Flex<"svg">;
  group300?: p.Flex<"div">;
  retweetContainer?: p.Flex<"div">;
  repeatIcon?: p.Flex<"svg">;
  frame215?: p.Flex<"div">;
  dateContainer?: p.Flex<"div">;
  timeContainer?: p.Flex<"div">;
};

export interface DefaultTwitterItem2Props {
  userName?: React.ReactNode;
  twitterHandle?: React.ReactNode;
  body?: React.ReactNode;
  image?: React.ReactNode;
  likes?: React.ReactNode;
  retweets?: React.ReactNode;
  date?: React.ReactNode;
  time?: React.ReactNode;
  composition?: SingleChoiceArg<"collapseImage" | "noImage">;
  className?: string;
}

function PlasmicTwitterItem2__RenderFunc(props: {
  variants: PlasmicTwitterItem2__VariantsArgs;
  args: PlasmicTwitterItem2__ArgsType;
  overrides: PlasmicTwitterItem2__OverridesType;
  dataFetches?: PlasmicTwitterItem2__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"contentTwitterPost3Image"}
        data-plasmic-override={overrides.contentTwitterPost3Image}
        hasGap={true}
        className={classNames(defaultcss.all, sty.contentTwitterPost3Image, {
          [sty.contentTwitterPost3Image__composition_collapseImage]: hasVariant(
            variants,
            "composition",
            "collapseImage"
          ),
          [sty.contentTwitterPost3Image__global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          )
        })}
      >
        <div
          data-plasmic-name={"twitterPostUser"}
          data-plasmic-override={overrides.twitterPostUser}
          className={classNames(defaultcss.all, sty.twitterPostUser)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"twitterUserContainer"}
            data-plasmic-override={overrides.twitterUserContainer}
            hasGap={true}
            className={classNames(defaultcss.all, sty.twitterUserContainer, {
              [sty.twitterUserContainer__composition_collapseImage]: hasVariant(
                variants,
                "composition",
                "collapseImage"
              )
            })}
          >
            <img
              data-plasmic-name={"twitterUserImage"}
              data-plasmic-override={overrides.twitterUserImage}
              alt={""}
              className={classNames(defaultcss.img, sty.twitterUserImage)}
              role={"img"}
              src={ellipse23PmI6Z3B0Xj}
            />

            <div
              data-plasmic-name={"twitterUserData"}
              data-plasmic-override={overrides.twitterUserData}
              className={classNames(defaultcss.all, sty.twitterUserData, {
                [sty.twitterUserData__composition_collapseImage]: hasVariant(
                  variants,
                  "composition",
                  "collapseImage"
                )
              })}
            >
              <div
                className={classNames(defaultcss.all, sty.freeBox__vhV7, {
                  [sty.freeBox__composition_collapseImage__vhV7MeBUw]:
                    hasVariant(variants, "composition", "collapseImage"),
                  [sty.freeBox__global_theme_dark__vhV7OIz4X]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {p.renderPlasmicSlot({
                  defaultContents: "@NavalBot",
                  value: args.twitterHandle,
                  className: classNames(sty.slotTwitterHandle, {
                    [sty.slotTwitterHandle__composition_collapseImage]:
                      hasVariant(variants, "composition", "collapseImage"),
                    [sty.slotTwitterHandle__global_theme_dark]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })
                })}
              </div>

              <div
                className={classNames(defaultcss.all, sty.freeBox___29UrG, {
                  [sty.freeBox__composition_collapseImage___29UrGmeBUw]:
                    hasVariant(variants, "composition", "collapseImage"),
                  [sty.freeBox__global_theme_dark___29UrGoIz4X]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {p.renderPlasmicSlot({
                  defaultContents: "Naval Ravikant Bot",
                  value: args.userName,
                  className: classNames(sty.slotUserName, {
                    [sty.slotUserName__composition_collapseImage]: hasVariant(
                      variants,
                      "composition",
                      "collapseImage"
                    ),
                    [sty.slotUserName__global_theme_dark]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })
                })}
              </div>
            </div>
          </p.Stack>
        </div>

        <div
          data-plasmic-name={"body"}
          data-plasmic-override={overrides.body}
          className={classNames(defaultcss.all, sty.body, {
            [sty.body__composition_collapseImage]: hasVariant(
              variants,
              "composition",
              "collapseImage"
            ),
            [sty.body__global_theme_dark]: hasVariant(
              globalVariants,
              "theme",
              "dark"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents:
              "Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.”",
            value: args.body,
            className: classNames(sty.slotBody, {
              [sty.slotBody__composition_collapseImage]: hasVariant(
                variants,
                "composition",
                "collapseImage"
              ),
              [sty.slotBody__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })
          })}
        </div>

        {(
          hasVariant(variants, "composition", "collapseImage") ? true : false
        ) ? (
          <div
            data-plasmic-name={"showImage"}
            data-plasmic-override={overrides.showImage}
            className={classNames(defaultcss.all, sty.showImage, {
              [sty.showImage__composition_collapseImage]: hasVariant(
                variants,
                "composition",
                "collapseImage"
              )
            })}
          >
            {(
              hasVariant(variants, "composition", "collapseImage")
                ? true
                : false
            ) ? (
              <IconarrowIosLeft2Icon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(defaultcss.all, sty.svg, {
                  [sty.svg__composition_collapseImage]: hasVariant(
                    variants,
                    "composition",
                    "collapseImage"
                  )
                })}
                role={"img"}
              />
            ) : null}
            {(
              hasVariant(variants, "composition", "collapseImage")
                ? true
                : false
            ) ? (
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__we3Dn,
                  {
                    [sty.freeBox__composition_collapseImage__we3DNmeBUw]:
                      hasVariant(variants, "composition", "collapseImage")
                  }
                )}
              >
                {hasVariant(variants, "composition", "collapseImage")
                  ? "show image "
                  : "Enter some text"}
              </div>
            ) : null}
          </div>
        ) : null}
        {(
          hasVariant(variants, "composition", "noImage")
            ? false
            : hasVariant(variants, "composition", "collapseImage")
            ? false
            : true
        ) ? (
          <div
            data-plasmic-name={"imageContainer"}
            data-plasmic-override={overrides.imageContainer}
            className={classNames(defaultcss.all, sty.imageContainer, {
              [sty.imageContainer__composition_collapseImage]: hasVariant(
                variants,
                "composition",
                "collapseImage"
              ),
              [sty.imageContainer__composition_noImage]: hasVariant(
                variants,
                "composition",
                "noImage"
              )
            })}
          >
            <div
              data-plasmic-name={"image"}
              data-plasmic-override={overrides.image}
              className={classNames(defaultcss.all, sty.image, {
                [sty.image__composition_collapseImage]: hasVariant(
                  variants,
                  "composition",
                  "collapseImage"
                ),
                [sty.image__composition_noImage]: hasVariant(
                  variants,
                  "composition",
                  "noImage"
                )
              })}
            >
              {p.renderPlasmicSlot({
                defaultContents: null,
                value: args.image
              })}
            </div>
          </div>
        ) : null}

        <div
          data-plasmic-name={"twitterPostMetaData"}
          data-plasmic-override={overrides.twitterPostMetaData}
          className={classNames(defaultcss.all, sty.twitterPostMetaData, {
            [sty.twitterPostMetaData__global_theme_dark]: hasVariant(
              globalVariants,
              "theme",
              "dark"
            )
          })}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"frame216"}
            data-plasmic-override={overrides.frame216}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame216, {
              [sty.frame216__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
          >
            <div
              data-plasmic-name={"group299"}
              data-plasmic-override={overrides.group299}
              className={classNames(defaultcss.all, sty.group299, {
                [sty.group299__composition_collapseImage]: hasVariant(
                  variants,
                  "composition",
                  "collapseImage"
                )
              })}
            >
              <div
                data-plasmic-name={"likesContainer"}
                data-plasmic-override={overrides.likesContainer}
                className={classNames(defaultcss.all, sty.likesContainer, {
                  [sty.likesContainer__composition_collapseImage]: hasVariant(
                    variants,
                    "composition",
                    "collapseImage"
                  )
                })}
              >
                <div
                  className={classNames(defaultcss.all, sty.freeBox__cz3I, {
                    [sty.freeBox__composition_collapseImage__cz3ImeBUw]:
                      hasVariant(variants, "composition", "collapseImage"),
                    [sty.freeBox__global_theme_dark__cz3IoIz4X]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "1.7k",
                    value: args.likes,
                    className: classNames(sty.slotLikes, {
                      [sty.slotLikes__composition_collapseImage]: hasVariant(
                        variants,
                        "composition",
                        "collapseImage"
                      ),
                      [sty.slotLikes__global_theme_dark]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })
                  })}
                </div>
              </div>

              <_27IconheartFillIcon
                data-plasmic-name={"heartIcon"}
                data-plasmic-override={overrides.heartIcon}
                className={classNames(defaultcss.all, sty.heartIcon, {
                  [sty.heartIcon__global_theme_dark]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"group300"}
              data-plasmic-override={overrides.group300}
              className={classNames(defaultcss.all, sty.group300)}
            >
              <div
                data-plasmic-name={"retweetContainer"}
                data-plasmic-override={overrides.retweetContainer}
                className={classNames(defaultcss.all, sty.retweetContainer, {
                  [sty.retweetContainer__composition_collapseImage]: hasVariant(
                    variants,
                    "composition",
                    "collapseImage"
                  )
                })}
              >
                <div
                  className={classNames(defaultcss.all, sty.freeBox__d5Z0, {
                    [sty.freeBox__composition_collapseImage__d5Z0MeBUw]:
                      hasVariant(variants, "composition", "collapseImage"),
                    [sty.freeBox__global_theme_dark__d5Z0OIz4X]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "372",
                    value: args.retweets,
                    className: classNames(sty.slotRetweets, {
                      [sty.slotRetweets__composition_collapseImage]: hasVariant(
                        variants,
                        "composition",
                        "collapseImage"
                      ),
                      [sty.slotRetweets__global_theme_dark]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })
                  })}
                </div>
              </div>

              <_27IconrepeatIcon
                data-plasmic-name={"repeatIcon"}
                data-plasmic-override={overrides.repeatIcon}
                className={classNames(defaultcss.all, sty.repeatIcon, {
                  [sty.repeatIcon__global_theme_dark]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
                role={"img"}
              />
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"frame215"}
            data-plasmic-override={overrides.frame215}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame215, {
              [sty.frame215__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
          >
            <div
              data-plasmic-name={"dateContainer"}
              data-plasmic-override={overrides.dateContainer}
              className={classNames(defaultcss.all, sty.dateContainer, {
                [sty.dateContainer__composition_collapseImage]: hasVariant(
                  variants,
                  "composition",
                  "collapseImage"
                ),
                [sty.dateContainer__global_theme_dark]: hasVariant(
                  globalVariants,
                  "theme",
                  "dark"
                )
              })}
            >
              <div
                className={classNames(defaultcss.all, sty.freeBox___8DzZ9, {
                  [sty.freeBox__composition_collapseImage___8DzZ9MeBUw]:
                    hasVariant(variants, "composition", "collapseImage"),
                  [sty.freeBox__global_theme_dark___8DzZ9OIz4X]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {p.renderPlasmicSlot({
                  defaultContents: "Mar 14",
                  value: args.date,
                  className: classNames(sty.slotDate, {
                    [sty.slotDate__composition_collapseImage]: hasVariant(
                      variants,
                      "composition",
                      "collapseImage"
                    ),
                    [sty.slotDate__global_theme_dark]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })
                })}
              </div>
            </div>

            <div
              data-plasmic-name={"timeContainer"}
              data-plasmic-override={overrides.timeContainer}
              className={classNames(defaultcss.all, sty.timeContainer, {
                [sty.timeContainer__composition_collapseImage]: hasVariant(
                  variants,
                  "composition",
                  "collapseImage"
                )
              })}
            >
              <div
                className={classNames(defaultcss.all, sty.freeBox__ewJip, {
                  [sty.freeBox__composition_collapseImage__ewJiPmeBUw]:
                    hasVariant(variants, "composition", "collapseImage"),
                  [sty.freeBox__global_theme_dark__ewJipoIz4X]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                {p.renderPlasmicSlot({
                  defaultContents: "8:00 PM",
                  value: args.time,
                  className: classNames(sty.slotTime, {
                    [sty.slotTime__composition_collapseImage]: hasVariant(
                      variants,
                      "composition",
                      "collapseImage"
                    ),
                    [sty.slotTime__global_theme_dark]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })
                })}
              </div>
            </div>
          </p.Stack>
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "contentTwitterPost3Image",
    "twitterPostUser",
    "twitterUserContainer",
    "twitterUserImage",
    "twitterUserData",
    "body",
    "showImage",
    "svg",
    "imageContainer",
    "image",
    "twitterPostMetaData",
    "frame216",
    "group299",
    "likesContainer",
    "heartIcon",
    "group300",
    "retweetContainer",
    "repeatIcon",
    "frame215",
    "dateContainer",
    "timeContainer"
  ],
  contentTwitterPost3Image: [
    "contentTwitterPost3Image",
    "twitterPostUser",
    "twitterUserContainer",
    "twitterUserImage",
    "twitterUserData",
    "body",
    "showImage",
    "svg",
    "imageContainer",
    "image",
    "twitterPostMetaData",
    "frame216",
    "group299",
    "likesContainer",
    "heartIcon",
    "group300",
    "retweetContainer",
    "repeatIcon",
    "frame215",
    "dateContainer",
    "timeContainer"
  ],
  twitterPostUser: [
    "twitterPostUser",
    "twitterUserContainer",
    "twitterUserImage",
    "twitterUserData"
  ],
  twitterUserContainer: [
    "twitterUserContainer",
    "twitterUserImage",
    "twitterUserData"
  ],
  twitterUserImage: ["twitterUserImage"],
  twitterUserData: ["twitterUserData"],
  body: ["body"],
  showImage: ["showImage", "svg"],
  svg: ["svg"],
  imageContainer: ["imageContainer", "image"],
  image: ["image"],
  twitterPostMetaData: [
    "twitterPostMetaData",
    "frame216",
    "group299",
    "likesContainer",
    "heartIcon",
    "group300",
    "retweetContainer",
    "repeatIcon",
    "frame215",
    "dateContainer",
    "timeContainer"
  ],
  frame216: [
    "frame216",
    "group299",
    "likesContainer",
    "heartIcon",
    "group300",
    "retweetContainer",
    "repeatIcon"
  ],
  group299: ["group299", "likesContainer", "heartIcon"],
  likesContainer: ["likesContainer"],
  heartIcon: ["heartIcon"],
  group300: ["group300", "retweetContainer", "repeatIcon"],
  retweetContainer: ["retweetContainer"],
  repeatIcon: ["repeatIcon"],
  frame215: ["frame215", "dateContainer", "timeContainer"],
  dateContainer: ["dateContainer"],
  timeContainer: ["timeContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  contentTwitterPost3Image: "div";
  twitterPostUser: "div";
  twitterUserContainer: "div";
  twitterUserImage: "img";
  twitterUserData: "div";
  body: "div";
  showImage: "div";
  svg: "svg";
  imageContainer: "div";
  image: "div";
  twitterPostMetaData: "div";
  frame216: "div";
  group299: "div";
  likesContainer: "div";
  heartIcon: "svg";
  group300: "div";
  retweetContainer: "div";
  repeatIcon: "svg";
  frame215: "div";
  dateContainer: "div";
  timeContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTwitterItem2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTwitterItem2__VariantsArgs;
    args?: PlasmicTwitterItem2__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTwitterItem2__Fetches;
  } & Omit<PlasmicTwitterItem2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTwitterItem2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTwitterItem2__ArgProps,
      internalVariantPropNames: PlasmicTwitterItem2__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTwitterItem2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTwitterItem2";
  } else {
    func.displayName = `PlasmicTwitterItem2.${nodeName}`;
  }
  return func;
}

export const PlasmicTwitterItem2 = Object.assign(
  // Top-level PlasmicTwitterItem2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    contentTwitterPost3Image: makeNodeComponent("contentTwitterPost3Image"),
    twitterPostUser: makeNodeComponent("twitterPostUser"),
    twitterUserContainer: makeNodeComponent("twitterUserContainer"),
    twitterUserImage: makeNodeComponent("twitterUserImage"),
    twitterUserData: makeNodeComponent("twitterUserData"),
    body: makeNodeComponent("body"),
    showImage: makeNodeComponent("showImage"),
    svg: makeNodeComponent("svg"),
    imageContainer: makeNodeComponent("imageContainer"),
    image: makeNodeComponent("image"),
    twitterPostMetaData: makeNodeComponent("twitterPostMetaData"),
    frame216: makeNodeComponent("frame216"),
    group299: makeNodeComponent("group299"),
    likesContainer: makeNodeComponent("likesContainer"),
    heartIcon: makeNodeComponent("heartIcon"),
    group300: makeNodeComponent("group300"),
    retweetContainer: makeNodeComponent("retweetContainer"),
    repeatIcon: makeNodeComponent("repeatIcon"),
    frame215: makeNodeComponent("frame215"),
    dateContainer: makeNodeComponent("dateContainer"),
    timeContainer: makeNodeComponent("timeContainer"),

    // Metadata about props expected for PlasmicTwitterItem2
    internalVariantProps: PlasmicTwitterItem2__VariantProps,
    internalArgProps: PlasmicTwitterItem2__ArgProps
  }
);

export default PlasmicTwitterItem2;
/* prettier-ignore-end */
