// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 24qDGfvb2rMn6oy8PVF95d
// Component: iAskgVxM_7
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_hub_hub.module.css"; // plasmic-import: 24qDGfvb2rMn6oy8PVF95d/projectcss
import * as sty from "./PlasmicItemTwitterFixed.module.css"; // plasmic-import: iAskgVxM_7/css

import _27IconheartFillIcon from "./icons/PlasmicIcon___27IconheartFill"; // plasmic-import: kGUtMm7VKf/icon
import _27IconrepeatIcon from "./icons/PlasmicIcon___27Iconrepeat"; // plasmic-import: DXysMN739Bs/icon
import ellipse193DfVm8Ngbpx from "./images/ellipse193.svg"; // plasmic-import: DfVm8Ngbpx/picture

export type PlasmicItemTwitterFixed__VariantMembers = {};

export type PlasmicItemTwitterFixed__VariantsArgs = {};
type VariantPropType = keyof PlasmicItemTwitterFixed__VariantsArgs;
export const PlasmicItemTwitterFixed__VariantProps =
  new Array<VariantPropType>();

export type PlasmicItemTwitterFixed__ArgsType = {};
type ArgPropType = keyof PlasmicItemTwitterFixed__ArgsType;
export const PlasmicItemTwitterFixed__ArgProps = new Array<ArgPropType>();

export type PlasmicItemTwitterFixed__OverridesType = {
  root?: p.Flex<"div">;
  contentTwitterPost2?: p.Flex<"div">;
  twitterPostUser?: p.Flex<"div">;
  frame229?: p.Flex<"div">;
  img?: p.Flex<"img">;
  frame228?: p.Flex<"div">;
  twitterPostMetaData?: p.Flex<"div">;
  frame216?: p.Flex<"div">;
  group299?: p.Flex<"div">;
  _17K?: p.Flex<"div">;
  group300?: p.Flex<"div">;
  _372?: p.Flex<"div">;
  frame215?: p.Flex<"div">;
  mar14?: p.Flex<"div">;
  _800Pm?: p.Flex<"div">;
  videoThumbnail?: p.Flex<"div">;
};

export interface DefaultItemTwitterFixedProps {
  className?: string;
}

function PlasmicItemTwitterFixed__RenderFunc(props: {
  variants: PlasmicItemTwitterFixed__VariantsArgs;
  args: PlasmicItemTwitterFixed__ArgsType;
  overrides: PlasmicItemTwitterFixed__OverridesType;
  dataFetches?: PlasmicItemTwitterFixed__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"contentTwitterPost2"}
        data-plasmic-override={overrides.contentTwitterPost2}
        className={classNames(defaultcss.all, sty.contentTwitterPost2)}
      >
        <div
          data-plasmic-name={"twitterPostUser"}
          data-plasmic-override={overrides.twitterPostUser}
          className={classNames(defaultcss.all, sty.twitterPostUser)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"frame229"}
            data-plasmic-override={overrides.frame229}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame229)}
          >
            <img
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(defaultcss.img, sty.img)}
              role={"img"}
              src={ellipse193DfVm8Ngbpx}
            />

            <div
              data-plasmic-name={"frame228"}
              data-plasmic-override={overrides.frame228}
              className={classNames(defaultcss.all, sty.frame228)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__sfCsz
                )}
              >
                {"@NavalBot"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__yQEg
                )}
              >
                {"Naval Ravikant Bot"}
              </div>
            </div>
          </p.Stack>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__c3Chh
          )}
        >
          {
            "Your goal in life is to find out the people who need you the most, to find out the business that needs you the most, to find the project and the art that needs you the most. There is something out there just for you.”"
          }
        </div>

        <div
          data-plasmic-name={"twitterPostMetaData"}
          data-plasmic-override={overrides.twitterPostMetaData}
          className={classNames(defaultcss.all, sty.twitterPostMetaData)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"frame216"}
            data-plasmic-override={overrides.frame216}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame216)}
          >
            <div
              data-plasmic-name={"group299"}
              data-plasmic-override={overrides.group299}
              className={classNames(defaultcss.all, sty.group299)}
            >
              <div
                data-plasmic-name={"_17K"}
                data-plasmic-override={overrides._17K}
                className={classNames(defaultcss.all, sty._17K)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___0JPpl
                  )}
                >
                  {"1.7k"}
                </div>
              </div>

              <_27IconheartFillIcon
                className={classNames(defaultcss.all, sty.svg__dgRaX)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"group300"}
              data-plasmic-override={overrides.group300}
              className={classNames(defaultcss.all, sty.group300)}
            >
              <div
                data-plasmic-name={"_372"}
                data-plasmic-override={overrides._372}
                className={classNames(defaultcss.all, sty._372)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__qBYyn
                  )}
                >
                  {"372"}
                </div>
              </div>

              <_27IconrepeatIcon
                className={classNames(defaultcss.all, sty.svg__ds1L4)}
                role={"img"}
              />
            </div>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"frame215"}
            data-plasmic-override={overrides.frame215}
            hasGap={true}
            className={classNames(defaultcss.all, sty.frame215)}
          >
            <div
              data-plasmic-name={"mar14"}
              data-plasmic-override={overrides.mar14}
              className={classNames(defaultcss.all, sty.mar14)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ck5NR
                )}
              >
                {"Mar 14"}
              </div>
            </div>

            <div
              data-plasmic-name={"_800Pm"}
              data-plasmic-override={overrides._800Pm}
              className={classNames(defaultcss.all, sty._800Pm)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__kjDL
                )}
              >
                {"8:00 PM"}
              </div>
            </div>
          </p.Stack>
        </div>

        <div
          data-plasmic-name={"videoThumbnail"}
          data-plasmic-override={overrides.videoThumbnail}
          className={classNames(defaultcss.all, sty.videoThumbnail)}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "contentTwitterPost2",
    "twitterPostUser",
    "frame229",
    "img",
    "frame228",
    "twitterPostMetaData",
    "frame216",
    "group299",
    "_17K",
    "group300",
    "_372",
    "frame215",
    "mar14",
    "_800Pm",
    "videoThumbnail"
  ],
  contentTwitterPost2: [
    "contentTwitterPost2",
    "twitterPostUser",
    "frame229",
    "img",
    "frame228",
    "twitterPostMetaData",
    "frame216",
    "group299",
    "_17K",
    "group300",
    "_372",
    "frame215",
    "mar14",
    "_800Pm",
    "videoThumbnail"
  ],
  twitterPostUser: ["twitterPostUser", "frame229", "img", "frame228"],
  frame229: ["frame229", "img", "frame228"],
  img: ["img"],
  frame228: ["frame228"],
  twitterPostMetaData: [
    "twitterPostMetaData",
    "frame216",
    "group299",
    "_17K",
    "group300",
    "_372",
    "frame215",
    "mar14",
    "_800Pm"
  ],
  frame216: ["frame216", "group299", "_17K", "group300", "_372"],
  group299: ["group299", "_17K"],
  _17K: ["_17K"],
  group300: ["group300", "_372"],
  _372: ["_372"],
  frame215: ["frame215", "mar14", "_800Pm"],
  mar14: ["mar14"],
  _800Pm: ["_800Pm"],
  videoThumbnail: ["videoThumbnail"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  contentTwitterPost2: "div";
  twitterPostUser: "div";
  frame229: "div";
  img: "img";
  frame228: "div";
  twitterPostMetaData: "div";
  frame216: "div";
  group299: "div";
  _17K: "div";
  group300: "div";
  _372: "div";
  frame215: "div";
  mar14: "div";
  _800Pm: "div";
  videoThumbnail: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicItemTwitterFixed__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicItemTwitterFixed__VariantsArgs;
    args?: PlasmicItemTwitterFixed__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicItemTwitterFixed__Fetches;
  } & Omit<PlasmicItemTwitterFixed__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicItemTwitterFixed__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicItemTwitterFixed__ArgProps,
      internalVariantPropNames: PlasmicItemTwitterFixed__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicItemTwitterFixed__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItemTwitterFixed";
  } else {
    func.displayName = `PlasmicItemTwitterFixed.${nodeName}`;
  }
  return func;
}

export const PlasmicItemTwitterFixed = Object.assign(
  // Top-level PlasmicItemTwitterFixed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    contentTwitterPost2: makeNodeComponent("contentTwitterPost2"),
    twitterPostUser: makeNodeComponent("twitterPostUser"),
    frame229: makeNodeComponent("frame229"),
    img: makeNodeComponent("img"),
    frame228: makeNodeComponent("frame228"),
    twitterPostMetaData: makeNodeComponent("twitterPostMetaData"),
    frame216: makeNodeComponent("frame216"),
    group299: makeNodeComponent("group299"),
    _17K: makeNodeComponent("_17K"),
    group300: makeNodeComponent("group300"),
    _372: makeNodeComponent("_372"),
    frame215: makeNodeComponent("frame215"),
    mar14: makeNodeComponent("mar14"),
    _800Pm: makeNodeComponent("_800Pm"),
    videoThumbnail: makeNodeComponent("videoThumbnail"),

    // Metadata about props expected for PlasmicItemTwitterFixed
    internalVariantProps: PlasmicItemTwitterFixed__VariantProps,
    internalArgProps: PlasmicItemTwitterFixed__ArgProps
  }
);

export default PlasmicItemTwitterFixed;
/* prettier-ignore-end */
