// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 24qDGfvb2rMn6oy8PVF95d
// Component: 12VCshRIS_
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_hub_hub.module.css"; // plasmic-import: 24qDGfvb2rMn6oy8PVF95d/projectcss
import * as sty from "./PlasmicFeedModeIcon.module.css"; // plasmic-import: 12VCshRIS_/css

export type PlasmicFeedModeIcon__VariantMembers = {
  selected: "selected";
};

export type PlasmicFeedModeIcon__VariantsArgs = {
  selected?: SingleBooleanChoiceArg<"selected">;
};

type VariantPropType = keyof PlasmicFeedModeIcon__VariantsArgs;
export const PlasmicFeedModeIcon__VariantProps = new Array<VariantPropType>(
  "selected"
);

export type PlasmicFeedModeIcon__ArgsType = {};
type ArgPropType = keyof PlasmicFeedModeIcon__ArgsType;
export const PlasmicFeedModeIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicFeedModeIcon__OverridesType = {
  root?: p.Flex<"div">;
  iconFeedView?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
  rectangle27?: p.Flex<"div">;
  rectangle30?: p.Flex<"div">;
};

export interface DefaultFeedModeIconProps {
  selected?: SingleBooleanChoiceArg<"selected">;
  className?: string;
}

function PlasmicFeedModeIcon__RenderFunc(props: {
  variants: PlasmicFeedModeIcon__VariantsArgs;
  args: PlasmicFeedModeIcon__ArgsType;
  overrides: PlasmicFeedModeIcon__OverridesType;
  dataFetches?: PlasmicFeedModeIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__selected]: hasVariant(variants, "selected", "selected")
      })}
    >
      <div
        data-plasmic-name={"iconFeedView"}
        data-plasmic-override={overrides.iconFeedView}
        className={classNames(defaultcss.all, sty.iconFeedView, {
          [sty.iconFeedView__selected]: hasVariant(
            variants,
            "selected",
            "selected"
          )
        })}
      >
        <div
          data-plasmic-name={"rectangle25"}
          data-plasmic-override={overrides.rectangle25}
          className={classNames(defaultcss.all, sty.rectangle25, {
            [sty.rectangle25__selected]: hasVariant(
              variants,
              "selected",
              "selected"
            )
          })}
        />

        <div
          data-plasmic-name={"rectangle26"}
          data-plasmic-override={overrides.rectangle26}
          className={classNames(defaultcss.all, sty.rectangle26)}
        />

        <div
          data-plasmic-name={"rectangle27"}
          data-plasmic-override={overrides.rectangle27}
          className={classNames(defaultcss.all, sty.rectangle27)}
        />
      </div>

      {(hasVariant(variants, "selected", "selected") ? true : false) ? (
        <div
          data-plasmic-name={"rectangle30"}
          data-plasmic-override={overrides.rectangle30}
          className={classNames(defaultcss.all, sty.rectangle30, {
            [sty.rectangle30__selected]: hasVariant(
              variants,
              "selected",
              "selected"
            )
          })}
        />
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "iconFeedView",
    "rectangle25",
    "rectangle26",
    "rectangle27",
    "rectangle30"
  ],
  iconFeedView: ["iconFeedView", "rectangle25", "rectangle26", "rectangle27"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle30: ["rectangle30"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  iconFeedView: "div";
  rectangle25: "div";
  rectangle26: "div";
  rectangle27: "div";
  rectangle30: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFeedModeIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFeedModeIcon__VariantsArgs;
    args?: PlasmicFeedModeIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicFeedModeIcon__Fetches;
  } & Omit<PlasmicFeedModeIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFeedModeIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFeedModeIcon__ArgProps,
      internalVariantPropNames: PlasmicFeedModeIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicFeedModeIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeedModeIcon";
  } else {
    func.displayName = `PlasmicFeedModeIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicFeedModeIcon = Object.assign(
  // Top-level PlasmicFeedModeIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iconFeedView: makeNodeComponent("iconFeedView"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle30: makeNodeComponent("rectangle30"),

    // Metadata about props expected for PlasmicFeedModeIcon
    internalVariantProps: PlasmicFeedModeIcon__VariantProps,
    internalArgProps: PlasmicFeedModeIcon__ArgProps
  }
);

export default PlasmicFeedModeIcon;
/* prettier-ignore-end */
